services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-17}
    restart: always
    command: ["-c", "wal_level=logical", "-c", "max_wal_senders=10", "-c", "max_replication_slots=10"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pglogrepl}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-pglogrepl}
      POSTGRES_HOST_AUTH_METHOD: trust
    network_mode: "host"
    ports:
      - "5432:5432"
    volumes:
      - ./test/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./test/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./test/pg_hba.conf:/etc/postgresql/pg_hba.conf
