name: dependabot-automerge
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: read

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'piusalfred/pglogrepl'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          skip-commit-verification: true
      - name: Label PR
        run: gh pr edit "$PR_URL" --add-label "automerge"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: Auto Approve PR
        run: gh pr review "$PR_URL" --approve --body "LGTM 😎"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable Auto Merge
        run: gh pr merge "$PR_URL" --auto --merge --squash --delete-branch --title "update dependencies" --body "dependencies updated by dependabot"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}