name: tasks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg-version: [ 15,16,17 ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.0'
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Lint Check
        run: task lint-check
      - name: run test for pg version ${{ matrix.pg-version }}
        run: task test-one POSTGRES_VERSION=${{ matrix.pg-version }}
        env:
          POSTGRES_VERSION: ${{ matrix.pg-version }}